language: python

addons:
  apt:
    packages:
	  - python3
	  - python3-pip
	  - python3-setuptools
	  - python3-wheel
	dist: bionic
	os: linux

install:
  - pip3 install phue
  - pip3 install cx_Freeze

build:
  - cd src
  - python setup.py build