language: python
os:
  - linux

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
      - python3-wheel
    dist: bionic
    os: linux

install:
  - pip3 install phue
  - pip3 install fbs PySide2
  - pip3 install requests
  - pip3 install --upgrade PyInstaller==3.5

script:
  - fbs freeze
